apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: state28
  labels:
    org.bstu.owner: "GrafShu"
    org.bstu.student.slug: "feis-576-220253-v28"
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: redis-ssd
  resources:
    requests:
      storage: 1Gi
