apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: state28
  labels:
    org.bstu.owner: "GrafShu"
    org.bstu.student.slug: "feis-576-220253-v28"
type: Opaque
stringData:
  password: "securepassword123"
